### ISSUE TITLE
返回数据的时候

### ISSUE THREAD

**Issue by shaobeichen** [zhixuanziben/gouyan-movie-vue#4]
Response {url: "/api/movie/coming_soon?callback=_jsonphm7kcvdkb6la89bpwqbedn29", ok: false, status: 0, statusText: "", headers: Headers…}
请求为0  这不是官方问题吧

**Comment by zhixuanziben** [comment]
不好意思，刚看到你的问题，这个问题我也不是很清楚是怎么导致的，实在抱歉
