### ISSUE TITLE
想咨询一下豆瓣api的问题

### ISSUE THREAD

**Issue by hizoubin** [zhixuanziben/gouyan-movie-vue#5]
豆瓣官方API中正在热映是商务权限的，我之前写demo直接用vue-resoure的jsonp方法无法获取到。你是怎么处理的呢？看你的代码也是直接jsonp得到的。

**Comment by zhixuanziben** [comment]
我的能正常获取到啊，如果官方的不能用，建议你用这个非官方版本的https://github.com/jokermonn/-Api/blob/master/DoubanMovie.md
