### ISSUE TITLE
$http.jsonp

### ISSUE THREAD

**Issue by zhangxintong** [zhixuanziben/gouyan-movie-vue#7]
this.$http.jsonp('https://api.douban.com/v2/movie/in_theaters')
        .then(function (response) {
            })
        .catch(function (response) {
          console.log(response)
        })
项目中用到的jsonp是在哪定义的我用的时候  报jsonp没有定义

**Comment by zhixuanziben** [comment]
这是vue-resource里的一个方法，你需要先安装vue-resource

**Comment by zhangxintong** [comment]
噢 我是想自己用react开发 也使用豆瓣接口 但是一直没有解决跨域访问的问题 正在查文档
